config/routes.rb
Got::Application.routes.draw do
  resources :users
  root 'characters#index' 
  resources :characters

end

app/models/character.rb
class Character < ActiveRecord::Base
  attr_accessible :storm_of_swords, :feast_for_crows, :breaking_the_law, :bolton_knows_best, :best_served_cold, :in_littlefingers_brothel, :you_win_or_you_die, :name

validates :name, :presence => true
validates :storm_of_swords, numericality: { only_integer: true }
validates :feast_for_crows, numericality: { only_integer: true }
validates :breaking_the_law, numericality: { only_integer: true }
validates :bolton_knows_best, numericality: { only_integer: true }
validates :best_served_cold, numericality: { only_integer: true }
validates :in_littlefingers_brothel, numericality: { only_integer: true }
validates :you_win_or_you_die, numericality: { only_integer: true }

def total_points
  self.storm_of_swords + self.feast_for_crows + self.breaking_the_law + self.bolton_knows_best + self.best_served_cold + self.in_littlefingers_brothel + self.you_win_or_you_die 
end

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :c1, :c2, :c3, :c4, :c5

  validates :name, :presence => true
  validates :c1, numericality: { only_integer: true }
  validates :c2, numericality: { only_integer: true }
  validates :c3, numericality: { only_integer: true }
  validates :c4, numericality: { only_integer: true }
  validates :c5, numericality: { only_integer: true }

  def total_points
  @c1 = Character.find(self.c1)
  @c2 = Character.find(self.c2)
  @c3 = Character.find(self.c3)
  @c4 = Character.find(self.c4)
  @c5 = Character.find(self.c5)

  @c1.total_points + @c2.total_points + @c3.total_points + @c4.total_points + @c5.total_points
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  def index
    @characters = Character.all.sort {|a,b| b.total_points <=> a.total_points}
  end

  def new
    @character = Character.new
  end

  def create
    @character = Character.new(params[:character])
    if @character.save
      redirect_to characters_path, :notice => "Successfully created character."
    else
      render :action => 'new'
    end
  end

  def edit
    @character = Character.find(params[:id])
  end

  def update
    @character = Character.find(params[:id])
    if @character.update_attributes(params[:character])
      redirect_to edit_character_path(@character), :notice => "Successfully updated character."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @character = Character.find(params[:id])
    @character.destroy
    redirect_to characters_url, :notice => "Successfully destroyed character."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.sort {|a,b| b.total_points <=> a.total_points}
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to users_path, :notice => "Successfully created user."
    else
      render :action => 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to edit_user_path(@user), :notice => "Successfully updated user."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_url, :notice => "Successfully destroyed user."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/characters/_form.html.erb
<%= form_for @character do |f| %>
    <% @character.errors.full_messages.each do |msg| %>
      <%= msg %><br>
    <% end %>
    <table width="100%">
      <tr>
        <td>
          <%= f.label :name %>
          <%= f.text_field :name %>
        </td>
        <td>
          <%= f.label :storm_of_swords %>
          <%= f.text_field :storm_of_swords%>
        </td>
      </tr> 
      <tr>
        <td>
          <%= f.label :feast_for_crows %>
          <%= f.text_field :feast_for_crows%>
        </td>
        <td>
          <%= f.label :breaking_the_law %>
          <%= f.text_field :breaking_the_law%>
        </td>
      </tr> 
      <tr>
        <td>
          <%= f.label :bolton_knows_best %>
          <%= f.text_field :bolton_knows_best %>
        </td>
        <td>
          <%= f.label :best_served_cold %>
          <%= f.text_field :best_served_cold%>
        </td>
      </tr> 
      <tr>
        <td>
          <%= f.label :in_littlefingers_brothel%>
          <%= f.text_field :in_littlefingers_brothel%>
        </td>
        <td>
          <%= f.label :you_win_or_you_die %>
          <%= f.text_field :you_win_or_you_die%>
        </td>
      </tr>
    </table> 
    <%= f.submit 'Submit', :class => 'button' %>
<% end %>

app/views/characters/edit.html.erb
<div class="row">
  <div class="small-6 small-centered columns">

    <h1>Edit <%= @character.name %></h1>
    <%= render 'form' %>
    <%= link_to "Back", characters_path %>
    <br>  

  </div>
</div>

app/views/characters/index.html.erb
<div class="row">
  <div class="small-6 small-centered columns">

<h1>Characters</h1>

<table width="100%">
  <thead>
    <th class="center">Name</th>
    <th class="center">Total Points</th>
  </thead>
  <% for character in @characters %>
    <tr>
      <td><%= link_to character.name, edit_character_path(character) %></td>
      <td><%= character.total_points %></td>
    </tr>
  <% end %>
</table>
  
  </div>
</div>

app/views/characters/new.html.erb
<div class="row">
  <div class="small-6 small-centered columns">

    <h1>New Character</h1>
    <%= render 'form' %>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Fantasy: Game of Thrones</title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body id="full">
   <div class="off-canvas-wrap" id="full">
    <div class="inner-wrap" id="full" >
      <nav class="tab-bar">
        <section class="left-small">
          <a class="left-off-canvas-toggle menu-icon" ><span></span></a>
        </section>

        <section class="middle tab-bar-section">
          <h1 class="title">Fantasy: Game of Thrones</h1>
        </section>
      </nav>

      <aside class="left-off-canvas-menu">
        <ul class="off-canvas-list">
          <li><label>Characters</label></li>
          <li><%= link_to "List All", characters_path %></li>
          <li><%= link_to "Add New", new_character_path %></li>
          <li><label>Users</label></li>
          <li><%= link_to "List All", users_path %></li>
          <li><%= link_to "Add New", new_user_path %></li>
        </ul>
      </aside>

      <section class="main-section center">
        <% flash.each do |name, msg| %>
          <% if msg.is_a?(String) %>
            <div data-alert class="alert-box <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
              <%= content_tag :div, msg %>
              <a href="#" class="close">&times;</a>
            </div>
          <% end %>
        <% end %>
        <!-- content goes here -->
                <%= yield %>
      </section>

    <a class="exit-off-canvas"></a>

    </div>
  </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
    <% @user.errors.full_messages.each do |msg| %>
      <%= msg %><br>
    <% end %>
    
    <table width="100%">
      <tr>
        <td width="50%">
          <%= f.label :name %>
          <%= f.text_field :name %>
        </td>
        <td>
          <%= f.label :c1 %>
          <%= f.collection_select :c1, Character.order(:name),:id,:name, include_blank: false %>
        </td>
      </tr>
      <tr>
        <td>
          <%= f.label :c2 %>
          <%= f.collection_select :c2, Character.order(:name),:id,:name, include_blank: false %>
        </td>
        <td>
          <%= f.label :c3 %>
          <%= f.collection_select :c3, Character.order(:name),:id,:name, include_blank: false %>
        </td>
      </tr>
      <tr>
        <td>
          <%= f.label :c4 %>
          <%= f.collection_select :c4, Character.order(:name),:id,:name, include_blank: false %>
        </td>
        <td>
          <%= f.label :c5 %>
          <%= f.collection_select :c5, Character.order(:name),:id,:name, include_blank: false %>
        </td>
      </tr>
    </table>
    <%= f.submit 'Submit', :class => 'button' %>
<% end %>

app/views/users/edit.html.erb
<div class="row">
  <div class="small-6 small-centered columns">

    <h1>Edit <%= @user.name %></h1>
    <%= render 'form' %>
    <%= link_to "Back", users_path %>
    <br>

  </div>
</div>

app/views/users/index.html.erb
<div class="row">
  <div class="small-6 small-centered columns">

<h1>All Users</h1>

<table width="100%">
  <thead>
    <th class="center">Name</th>
    <th class="center">Total Points</th>
  </thead>
  <% for user in @users %>
    <tr>
      <td><%= link_to user.name, edit_user_path(user) %></td>
      <td><%= user.total_points %></td>
    </tr>
  <% end %>
</table>

  </div>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="small-6 small-centered columns">

<h1>New User</h1>
<%= render 'form' %>

  </div>
</div>